# **Affects of Barge Movements on the Environment**

By Madeline Nellis and Caroline Casella

[Github Repository Link](https://github.com/madelinenellis/madelinenellis.github.io)

For our final project, we are interested in researching how varying rates of barge movements down the Mississippi river affect the air quality, water quality, effect on wildlife, and the sinking of New Orleans. The USDA provides information on barge movements through New Orleans and Jefferson Parish with multiple data sets regarding the commodity or material, season, locks, and location along the river. We plan to use these datasets to analyze the effect of increased rates of barge traffic with air quality and water quality data. We will compare these two sets of data in order to research their overlap and reach a possible conclusion. 

For this milestone we have loaded the barge movement data into a jupyter notebook. This data was already easy to read and demonstrated the principles of tidy data, but we added a column to show the tons moved per week on the barges to help our analysis. One of the biggest challenges for this data was choosing which fields to extract from the database. There are many different options and since we haven’t done much analysis yet it is hard to predict what we may need. We extracted what we thought would be best for our analysis for now, but will most likely have to go back and pull other fields from the database.

We are still in pursuit of finding datasets that accurately encompass the rates of wildlife and land loss, but if we are able to discover data that would be usable, we would definitely incorporate those findings into our final project. These datasets would be particularly useful in answering questions regarding the long-term impact of barges due to the lack of natural soil dispersion and over use of dredging. Water quality data of the Mississippi could also provide us with valuable findings regarding wildlife diversity loss. 

We have discussed how we plan to collaborate on the project and we decided to have weekly catch up meetings and discuss what else we want to accomplish for that week. We have set up a private GitHub repo that we will use to share our findings and code with one another.

In [1]:
# first, mount your google drive, change to the course folder, pull latest changes, and change to the lab folder.
from google.colab import drive
drive.mount('/content/drive')
%cd /content/drive/My Drive/Data-Science-Project

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
/content/drive/My Drive/Data-Science-Project

In [2]:
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
# Read in Barge Movement file
df = pd.read_csv("DownboundBarge.csv")
df

             Date  Week  Month  Year    Commodity           Lock      Tons
0      06/27/2020    26      6  2020         Corn     Ark Lock 1    1400.0
1      06/27/2020    26      6  2020  Other Grain     Ark Lock 1       0.0
2      06/27/2020    26      6  2020     Soybeans     Ark Lock 1   11200.0
3      06/27/2020    26      6  2020        Wheat     Ark Lock 1   23800.0
4      06/27/2020    26      6  2020         Corn  Miss Locks 27  452800.0
...           ...   ...    ...   ...          ...            ...       ...
12367  10/01/2022    39      9  2022        Wheat  Miss Locks 27    1600.0
12368  10/01/2022    39      9  2022         Corn   Ohio Olmsted   54550.0
12369  10/01/2022    39      9  2022  Other Grain   Ohio Olmsted       0.0
12370  10/01/2022    39      9  2022     Soybeans   Ohio Olmsted   45850.0
12371  10/01/2022    39      9  2022        Wheat   Ohio Olmsted    1750.0

[12372 rows x 7 columns]

In [4]:
# Generate table with total number of tons moved per week
tonsPerWeek = df.groupby('Week', as_index=True).agg({'Tons': 'sum'})
tonsPerWeek.head()

            Tons
Week
1     10286625.0
2     11823686.0
3     12814818.0
4     12552222.0
5     12009027.0

In [14]:
#Generate table with total number of tons per commodity
mostMovedCommodity = df.groupby('Commodity', as_index=True).agg({'Tons': 'sum'})
mostMovedCommodity

                    Tons
Commodity
Corn         420725635.0
Other Grain    8220839.0
Soybeans     223048957.0
Wheat         38194050.0

In [20]:
#Tons of Each Commodity Per Week
mostMovedCommodityPerWeek = df.groupby(["Week", "Commodity"])["Tons"].sum()
mostMovedCommodityPerWeek

Week  Commodity
1     Corn           5239212.0
      Other Grain     195609.0
      Soybeans       4418473.0
      Wheat           433331.0
2     Corn           6110265.0
                       ...
52    Wheat           361710.0
53    Corn           1280197.0
      Other Grain      14400.0
      Soybeans        978801.0
      Wheat            67154.0
Name: Tons, Length: 212, dtype: float64

In [31]:
%%shell
jupyter nbconvert --to html DS-Milestone1.ipynb

[NbConvertApp] Converting notebook DS-Milestone1.ipynb to html
[NbConvertApp] Writing 307843 bytes to DS-Milestone1.html